echo "drush"
alias dca="drush cc all"
alias ddis="drush ds"
alias ddl="drush dl"
alias den="drush en"
alias dls="drush pml"
alias dre="drush dre"
alias dlsen="drush pml | grep -i enable"
alias dlsdis="drush pml | grep -i disabled"
alias dlsni="drush pml | grep -i not"
alias ddcs="drush dcs"
alias dformat="drush coder-format"
alias drev="drush coder-review"
alias dmg="drush make-generate"
alias dmake="drush make"
